# Generated by Django 3.2.9 on 2021-11-30 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_enrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='due_cleared',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='pan_number',
            field=models.TextField(max_length=10),
        ),
    ]
