# Generated by Django 3.2.9 on 2021-12-02 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_emi'),
    ]

    operations = [
        migrations.AddField(
            model_name='emi',
            name='dealer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.dealer'),
        ),
    ]
