# Generated by Django 3.2.9 on 2021-12-02 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_emi_dealer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emi',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
